### ISSUE TITLE
Export Entry Point

### ISSUE THREAD

**Issue by hasherezade** [hasherezade/exe_to_dll#1]
Currently only loading of the EXE as a DLL is supported. But in order to call any function, we must manually find and call its address.

For easier use, it would be beneficial to have the export table created, and the Original Entry Point should be added as an exported function.

**Comment by websecnl** [comment]
So what is the main entry point name, lets say I want to run it with rundll32 ?

This is not working: testload x.dll dllmain

**Comment by hasherezade** [comment]
@websecnl as it is mentioned in the parameters description, `testload` requires you to give the `RVA` of the function, not the name: 
https://github.com/hasherezade/exe_to_dll/blob/master/testload/main.cpp#L18

**Comment by hasherezade** [comment]
Implemented in the release [1.1](https://github.com/hasherezade/exe_to_dll/releases/tag/1.1)
