### ISSUE TITLE
Hi im a french guy with a bad english who sux at tech

### ISSUE THREAD

**Issue by GayBastard** [hasherezade/exe_to_dll#3]
hi i dont understand how to use it
can you tell me how pls ?
and is it possible to run it with rundll32 ?

**Comment by hasherezade** [comment]
Hi! No, it has nothing to deal with `rundll32.exe`. It is to convert a DLL into EXE as described here: https://blog.vastart.dev/2020/04/calling-arbitrary-functions-in-exes.html (it can be a helper to simplify some tasks related to reverse engineering).
If you are not familiar with those things, then probably you are not the target group of this tool.
